import {
  Bell,
  Bluetooth,
  Video,
  Camera,
  AlertCircle,
  Sun,
  Circle,
  Monitor,
  Activity,
  AlertTriangle,
  Usb,
  List,
  Home,
  Car,
  CarFront,
  CalendarDays,
  CircleUser,
  Wallet,
  CircleDollarSign,
  ArrowRightLeft,
  ArrowLeftRight,
  Star,
  KeyRound,
  DollarSign,
  ArrowLeft,
  PlusCircle,
  MapPin,
  ChevronDown,
  Edit,
  Shield,
  LogOut,
  ChevronLeft,
  EllipsisVertical,
  Dot,
  Plus,
  Layers,
  Fuel,
  Snowflake,
  Armchair,
  Wifi,
  Briefcase,
  Cog,
  Shell,
  Map,
} from 'lucide-react-native';

import { iconWithClassName } from './iconWithClassName';

iconWithClassName(Bell);
iconWithClassName(Bluetooth);
iconWithClassName(Video);
iconWithClassName(Camera);
iconWithClassName(AlertCircle);
iconWithClassName(Sun);
iconWithClassName(Circle);
iconWithClassName(Monitor);
iconWithClassName(Activity);
iconWithClassName(AlertTriangle);
iconWithClassName(Usb);
iconWithClassName(List);
iconWithClassName(ChevronDown);
iconWithClassName(Home);
iconWithClassName(Car);
iconWithClassName(CarFront);
iconWithClassName(CalendarDays);
iconWithClassName(CircleUser);
iconWithClassName(Wallet);
iconWithClassName(CircleDollarSign);
iconWithClassName(ArrowRightLeft);
iconWithClassName(ArrowLeftRight);
iconWithClassName(Star);
iconWithClassName(KeyRound);
iconWithClassName(DollarSign);
iconWithClassName(ArrowLeft);
iconWithClassName(PlusCircle);
iconWithClassName(MapPin);
iconWithClassName(Edit);
iconWithClassName(Shield);
iconWithClassName(LogOut);
iconWithClassName(ChevronLeft);
iconWithClassName(EllipsisVertical);
iconWithClassName(Dot);
iconWithClassName(Plus);
iconWithClassName(Layers);
iconWithClassName(Fuel);
iconWithClassName(Snowflake);
iconWithClassName(Armchair);
iconWithClassName(Wifi);
iconWithClassName(Briefcase);
iconWithClassName(Cog);
iconWithClassName(Shell);
iconWithClassName(Map);

export {
  Map,
  Bell,
  Bluetooth,
  Video,
  Camera,
  AlertCircle,
  Sun,
  Circle,
  Monitor,
  Activity,
  AlertTriangle,
  Usb,
  List,
  Home,
  Car,
  CarFront,
  CalendarDays,
  CircleUser,
  Wallet,
  CircleDollarSign,
  ArrowRightLeft,
  ArrowLeftRight,
  Star,
  KeyRound,
  DollarSign,
  ArrowLeft,
  PlusCircle,
  MapPin,
  ChevronDown,
  Edit,
  Shield,
  LogOut,
  ChevronLeft,
  EllipsisVertical,
  Dot,
  Plus,
  Layers,
  Fuel,
  Snowflake,
  Armchair,
  Wifi,
  Briefcase,
  Cog,
  Shell,
};
