export interface BookParams extends Partial<LastIdRootResquest> {
  search: string;
  status: string;
  isPaid: boolean;
}

export interface BookPayload {
  carId: string;
  startTime: Date;
  endTime: Date;
}

export interface BookFeedbackPayload {
  rating: number;
  comment: string;
}

export interface BookResponseList {
  id: string;
  carName: string;
  driverName: string;
  ownerName: string;
  totalAmount: number;
  totalDistance: number;
  isPaid: boolean;
  status: string;
  startTime: Date;
  endTime: Date;
  actualReturnTime: Date;
}
export interface BookResponseDetail {
  // Generated by https://quicktype.io

  id: string;
  car: Car;
  driver: Driver;
  owner: Driver;
  booking: Booking;
  payment: Payment;
  trip: Trip;
  feedbacks: Feedback[];
}

export interface Booking {
  startTime: Date;
  endTime: Date;
  actualReturnTime: Date;
  totalDistance: number;
  status: string;
  note: string;
}

export interface Car {
  id: string;
  modelName: string;
  licensePlate: string;
  color: string;
  seat: number;
  transmissionType: string;
  fuelType: string;
}

export interface Driver {
  id: string;
  name: string;
  phone: string;
  email: string;
}

export interface Feedback {
  id: string;
  rating: number;
  content: string;
  type: string;
  userName: string;
}

export interface Payment {
  basePrice: number;
  platformFee: number;
  excessDay: number;
  excessDayFee: number;
  totalAmount: number;
  isPaid: boolean;
}

export interface Trip {
  totalDistance: number;
}

export interface BookTrackBatchPayload {
  locationPoints: LocationPoint[];
}

export interface LocationPoint {
  latitude: number;
  longitude: number;
  createdAt: Date;
}

export interface BookTrackPayload {
  latitude: number;
  longitude: number;
}

export interface Webhook {
  code: string;
  desc: string;
  success: boolean;
  data: Data;
  signature: string;
}

export interface Data {
  orderCode: number;
  amount: number;
  description: string;
  accountNumber: string;
  reference: string;
  transactionDateTime: string;
  currency: string;
  paymentLinkId: string;
  code: string;
  desc: string;
  counterAccountBankId: string;
  counterAccountBankName: string;
  counterAccountName: string;
  counterAccountNumber: string;
  virtualAccountName: string;
  virtualAccountNumber: string;
}
